name: Tests

on:
  pull_request:
    branches: ['main']
    paths-ignore:
      - 'README.md'
  push:
    branches: ['main']
    paths-ignore:
      - 'README.md'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go build -v .
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: '1.5.*'
          terraform_wrapper: false
      - run: go mod download
      - env:
          TF_ACC: "1"
        timeout-minutes: 10
        run: |
          echo pwd is $(pwd)
          TF_MELANGE_OUT=$(pwd) go test -v -cover ./internal/provider/

      - if: ${{always()}}
        run: |
          tree ./packages/

          cat ./packages/x86_64/*.log

      - if: ${{ failure() }}
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: logs-${{github.run_id}}
          path: ${{github.workspace}}/internal/provider/packages
          retention-days: 1
